# Generated by Django 5.2.14 on 2026-06-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_diabloqueado'),
        ('agendamento', '0003_planoassinatura_assinatura'),
    ]

    operations = [
    ]
