# Generated by Django 5.2.14 on 2026-06-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_merge_20260620_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='plano',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='PlanoAssinatura',
        ),
        migrations.DeleteModel(
            name='Assinatura',
        ),
    ]
