# Generated by Django 5.2.14 on 2026-06-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_horariodisponivel_remove_assinatura_plano_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(default='Agenda Fácil', max_length=100)),
                ('texto_home', models.CharField(default='Agende serviços de forma simples, rápida e organizada.', max_length=200)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos/')),
                ('paleta_cores', models.CharField(choices=[('verde_institucional', 'Verde institucional'), ('azul_profissional', 'Azul profissional'), ('areia_minimalista', 'Areia minimalista')], default='verde_institucional', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='servico',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
