# Generated by Django 5.2.14 on 2026-06-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_configuracaosite_servico_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='titulo_home',
            field=models.CharField(default='Filmagens aéreas profissionais com drones', max_length=120),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='nome_site',
            field=models.CharField(default='Atobá Drones', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='texto_home',
            field=models.CharField(default='Agende seu serviço com segurança, qualidade e planejamento.', max_length=200),
        ),
    ]
