# Generated by Django 5.2.14 on 2026-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_configuracaosite_titulo_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosite',
            name='paleta_cores',
            field=models.CharField(choices=[('verde_institucional', 'Verde institucional'), ('azul_profissional', 'Azul profissional'), ('areia_minimalista', 'Areia minimalista'), ('preto_premium', 'Preto premium'), ('grafite_tecnologico', 'Grafite tecnológico'), ('azul_marinho_executivo', 'Azul marinho executivo'), ('vermelho_energia', 'Vermelho energia'), ('laranja_criativo', 'Laranja criativo'), ('roxo_moderno', 'Roxo moderno'), ('rosa_elegante', 'Rosa elegante'), ('verde_saude', 'Verde saúde'), ('azul_claro_leve', 'Azul claro leve'), ('marrom_artesanal', 'Marrom artesanal')], default='verde_institucional', max_length=30),
        ),
    ]
