# Generated by Django 5.2.14 on 2026-06-24 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0008_alter_configuracaosite_paleta_cores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status_pagamento', models.CharField(choices=[('aguardando_pagamento', 'Aguardando pagamento'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('expirado', 'Expirado')], default='aguardando_pagamento', max_length=30)),
                ('pagamento_id', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.cliente')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.localatendimento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.servico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
