# Generated by Django 5.2.14 on 2026-06-24 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0009_pedidopendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopendente',
            name='agendamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamento.agendamento'),
        ),
        migrations.AddField(
            model_name='pedidopendente',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedidopendente',
            name='asaas_invoice_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pedidopendente',
            name='asaas_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
